name: Crowdin sync action

on:
  push:
    branches: [ develop ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version-file: ".nvmrc"
    - name: crowdin sync
      run: |
        npm install -g yarn && yarn install
        git config --global user.name "trezor-ci"
        git config --global user.email "${{ secrets.TREZOR_BOT_EMAIL }}"
        git checkout -B trezor-ci/crowdin-sync
        yarn workspace @trezor/suite translations:download --token=${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        git add . && git commit -m "chore: crowdin translation update" && git push origin trezor-ci/crowdin-sync
        gh config set prompt disabled
        gh pr create --repo vdovhanych/trezor-suite --title "crowdin translation update" --body "Sync of crowdin translations into develop." --base develop --label translations
      env:
        GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
