name: Crowdin Action

on:
  push:
    branches: [ develop ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version-file: ".nvmrc"
    - name: Setup yarn
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - name: crowdin sync
      run: |
        git checkout -B trezor-ci/crowdin-sync
        yarn workspace @trezor/suite translations:download --token=${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        gh pr create --repo vdovhanych/trezor-suite --title "crowdin translation update" --body "Sync of crowdin translations into develop." --base develop
      env:
        GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
