name: Crowdin Action

on:
  push:
    branches: [ develop ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.6
      with:
        upload_sources: false
        download_translations: true
        localization_branch_name: trezor-ci/crowdin_update
        commit_message: "chore: update translations from crowdin"
        pull_request_title: 'chore: update translations from crowdin'
        pull_request_body: 'automated update of crowdin translations'
        pull_request_labels: 'translations'
        create_pull_request: true

      env:
        GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
